import = ["/home/max/.config/alacritty/dist/themes/nightfox.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 11.75

# [env]
# WINIT_X11_SCALE_FACTOR = "1.25"

[font.normal]
family = "MononokiNerdFontMono"
# family = "SauceCodeProNerdFontMono"
# family = "MesloLGS NF"
# family = "LilexNerdFontMono"

[scrolling]
history = 1000
multiplier = 3

[shell]
program = "/usr/bin/zsh"

[window]
# decorations = "none"
opacity = 0.84
startup_mode = "maximized"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
#x = 10
#y = 10

[debug]
print_events = true
